<script type=”text/javascript”>

def_test_MartinVidalGarcia = 
Array(
    Array('id_programa',1,'longitud < 1',false,'id_programa debe de contener al menos un digito'),
    Array('id_programa',2,'longitud > 6',false,'id_programa debe tener maximo 6 digitos'),
    Array('id_programa',3,'introducir letras',false,'id_programa debe estar compuesto por digitos'),
    Array('id_programa',4,'introducir caracteres especiales',false,'id_programa solamente permite digitos'),
    Array('nombre_programa',1,'longitud < 6',false,'nombre_programa demasiado corto, debe tener por lo menos 6 caracteres'),
    Array('nombre_programa',2,'longitud > 60',false,'nombre_programa demasiado largo, como maximo debe tener 60 caracteres'),
    Array('nombre_programa',3,'existen digitos',false,'nombre_programa solamente permite formato alfabetico'),
    Array('nombre_programa',4,'caracteres especiales',false,'nombre_programa debe de limitarse a carateres, incluidos ["acentos", "ñ", "espacios"]'),
    Array('acronimo_programa',1,'longitud < 3',false,'acronimo_programa demasiado corto, debe tener por lo menos 3 caracteres'),
    Array('acronimo_programa',2,'longitud > 20',false,'acronimo_programa demasiado largo, como maximo debe tener 20 caracteres'),
    Array('acronimo_programa',3,'existen digitos',false,'acronimo_programa solamente permite formato alfabetico'),
    Array('acronimo_programa',4,'caracteres especiales',false,'acronimo_programa solamente permite alfabeticos sin acentos ni espacios'),
    Array('nombre_original_programa',1,'longitud < 6',false,'nombre_original_programa demasiado corto, debe tener por lo menos 6 caracteres'),
    Array('nombre_original_programa',2,'longitud > 60',false,'nombre_original_programa demasiado largo, como maximo debe tener 60 caracteres'),
    Array('nombre_original_programa',3,'existen digitos',false,'nombre_original_programa solamente permite formato alfabetico'),
    Array('nombre_original_programa',4,'caracteres especiales',false,'nombre_original_programa debe limitarse a caracteres incluidos ["acentos", "ñ", "espacios"]'),
    Array('autor_programa',1,'longitud < 6',false,'autor_programa demasiado corto, debe tener por lo menos 6 caracteres'),
    Array('autor_programa',2,'longitud > 50',false,'autor_programa demasiado largo, como maximo debe tener 50 caracteres'),
    Array('autor_programa',3,'existen digitos',false,'autor_programa solamente permite formato alfabetico'),
    Array('autor_programa',4,'caracteres especiales',false,'autor_programa debe limitarse a caracteres incluidos ["acentos", "ñ", "espacios"]'),
    Array('autor_orginal_programa',1,'longitud < 6',false,'autor_original_programa demasiado corto, debe tener por lo menos 6 caracteres'),
    Array('autor_orginal_programa',2,'longitud > 50',false,'autor_original_programa demasiado largo, como maximo debe tener 50 caracteres'),
    Array('autor_orginal_programa',3,'existen digitos',false,'autor_original_programa solamente permite formato alfabetico'),
    Array('autor_orginal_programa',4,'caracteres especiales',false,'autor_original_programa debe limitarse a caracteres incluidos ["acentos", "ñ", "espacios"]'),
    Array('ano_programa',1,'longitud < 4',false,'ano_programa demasiado corto, debe te contener 4 digitos'),
    Array('ano_programa',2,'longitud > 4',false,'ano_programa demasiado largo, debe te contener 4 digitos'),
    Array('ano_programa',3,'año superior al actual',false,'ano_programa no puede ser superior al año actual'),
    Array('ano_programa',4,'introducir letras',false,'ano_programa no puede contener letras, solamente digitos'),
    Array('ano_programa',5,'introducir caracteres especiales',false,'ano_programa solamente admite digitos'),
    Array('ano_original_programa',1,'longitud < 4',false,'ano_original_programa demasiado corto, debe te contener 4 digitos'),
    Array('ano_original_programa',2,'longitud > 4',false,'ano_original_programa demasiado largo, debe te contener 4 digitos'),
    Array('ano_original_programa',3,'año superior al actual',false,'ano_original_programa no puede ser superior al año actual'),
    Array('ano_original_programa',4,'introducir letras',false,'ano_original_programa no puede contener letras, solamente digitos'),
    Array('ano_original_programa',5,'introducir caracteres especiales',false,'ano_original_programa solamente admite digitos'),
    Array('requisitos_programa',1,'longitud < 6',false,'requisitos_programa demasiado corto, debe contener al menos 6 caracteres'),
    Array('requisitos_programa',2,'longitud > 300',false,'requisitos_programa demasiado largo, como maximo debe contener 300 caracteres'),
    Array('requisitos_programa',3,'incluir numeros',false,'requisitos_programa solamente permite formato alfabetico'),
    Array('requisitos_programa',4,'caracteres especiales',false,'requisitos_programa debe limitarse a caracteres incluidos ["acentos", "ñ", "espacios", "signos de puntuacion"]'),
    Array('poblacion_desde_programa',1,'longitud < 1',false,'poblacion_desde_programa debe incluir al menos 1 digito'),
    Array('poblacion_desde_programa',2,'longitud > 2',false,'poblacion_desde_programa debe tener como maximo 2 digitos'),
    Array('poblacion_desde_programa',3,'incluir letras',false,'poblacion_desde_programa solemente permite numeros'),
    Array('poblacion_desde_programa',4,'incluir caracteres especiales',false,'poblacion_desde_programa no permite caracteres especiales, solamente digitos'),
    Array('poblacion_hasta_programa',1,'longitud < 1',false,'poblacion_hasta_programa debe incluir al menos 1 digito'),
    Array('poblacion_hasta_programa',2,'longitud > 2',false,'poblacion_hasta_programa debe tener como maximo 2 digitos'),
    Array('poblacion_hasta_programa',3,'incluir letras',false,'poblacion_hasta_programa solemente permite numeros'),
    Array('poblacion_hasta_programa',4,'incluir caracteres especiales',false,'poblacion_hasta_programa no permite caracteres especiales, solamente digitos'),
    Array('unidad_poblacion',1,'introducir digitos',false,'unidad_poblacion solamente permite caracteres alfabeticos'),
    Array('unidad_poblacion',2,'introducir cadenas distintas a las permitidas',false,'unidad_poblacion solamente permite  ["MESES", "AÑOS"]'),
    Array('unidad_poblacion',3,'introducir caracteres especiales',false,'unidad_poblacion no permite caracteres especiales'),
    Array('tipo_programa',1,'introducir digitos',false,'tipo_programa no permite valores numericos'),
    Array('tipo_programa',2,'introducir cadenas distintas a las permitidas',false,'tipo_programa solamente permite ["EVALUCACION", "INTERVENCION", "EVALUCACION E INTERVENCION"]'),
    Array('tipo_programa',3,'introducir caracteres especiales',false,'tipo_programa no permite caracteres especiales'),
    Array('tipo_aplicacion_programa',1,'longitud < 1',false,'tiempo_aplicacion_programa debe incluir al menos 1 digito'),
    Array('tipo_aplicacion_programa',2,'longitud > 4',false,'tiempo_aplicacion_programa debe tener como maximo 4 digitos'),
    Array('tipo_aplicacion_programa',3,'incluir letras',false,'tiempo_aplicacion_programa solemente permite numeros'),
    Array('tipo_aplicacion_programa',4,'incluir caracteres especiales',false,'tiempo_aplicacion_programa no permite caracteres especiales, solamente digitos'),
    Array('descrip_interp_programa',1,'introducir digitos',false,'descrip_interp_programa no permite valores numericos'),
    Array('descrip_interp_programa',2,'introducir caracteres especiales',false,'descrip_interp_programa solamente permite caracteres especiales como ["ñ", "espacio", "letras con acentos", "signos de puntuacion", "retorno de carro"]'),
    Array('descrip_interp_programa',3,'longitud < 100',false,'descrip_interp_programa debe tener como m�nimo 100 caracteres'),
    Array('descrip_interp_programa',4,'longitud > 5000',false,'descrip_interp_programa no acepta m�s de 5000 caracteres'),
    Array('fichero_programa',1,'longitud < 7',false,'fichero_programa demasiado corto, debe tener por lo menos 7 caracteres'),
    Array('fichero_programa',2,'longitud > 60',false,'fichero_programa demasiado largo, como maximo debe tener 60 caracteres'),
    Array('fichero_programa',3,'existen digitos',false,'fichero_programa solamente permite formato alfabetico'),
    Array('fichero_programa',4,'caracteres especiales',false,'fichero_programa debe limitarse a caracteres incluidos ["acentos", "ñ", "espacios"]'),
    Array('enlace_programa',1,'introducir digitos',false,'enlace_programa no permite digitos, solamente caracteres alfabeticos'),
    Array('enlace_programa',2,'caracteres especiales',false,'enlace_programa solamente permite [":", "/","."], no permite ñ ni espacios'),
    Array('enlace_programa',3,'longitud < 10',false,'enlace_programa debe tener como minimo 10 caracteres alfabeticos'),
    Array('enlace_programa',4,'longitud > 100',false,'enlace_programa como maximo permite 100 caracteres alfabeticos'),
    Array('formato_programa',1,'introducir digitos',false,'formato_programa solamente permite caracteres alfabeticos'),
    Array('formato_programa',2,'introducir caracteres especiales',false,'formato_programa no permite caracteres especiales'),
    Array('formato_programa',3,'introducir cadenas distintas a las permitidas',false,'formato_programa no permite cadenas de caracteres distintas a ["PAPEL", "ELECTRONICO", "PAPEL Y ELECTRONICO"]'),
    Array('modo_correccion_programa',1,'introducir digitos',false,'modo_correccion_programa solamente permite caracteres alfabeticos'),
    Array('modo_correccion_programa',2,'introducir caracteres especiales',false,'modo_correccion_programa no permite caracteres especiales'),
    Array('modo_correccion_programa',3,'introducir cadenas distintas a las permitidas',false,'modo_correccion_programa no permite cadenas de caracteres distintas a ["PAPEL", "ELECTRONICO", "PAPEL Y ELECTRONICO"]'),
    Array('modo_aplicacion_programa',1,'introducir digitos',false,'modo_aplicacion_programa solamente permite caracteres alfabeticos'),
    Array('modo_aplicacion_programa',2,'introducir caracteres especiales',false,'modo_aplicacion_programa no permite caracteres especiales'),
    Array('modo_aplicacion_programa',3,'introducir cadenas distintas a las permitidas',false,'modo_aplicacion_programa no permite cadenas de caracteres distintas a ["INDIVIDUAL", "COLECTIVO", "INDIVIDUAL Y COLECTIVO"]'),
    Array('imagen_programa',1,'longitud < 7',false,'imagen_programa demasiado corto, debe tener por lo menos 7 caracteres'),
    Array('imagen_programa',2,'longitud > 60',false,'imagen_programa demasiado largo, como maximo debe tener 60 caracteres'),
    Array('imagen_programa',3,'existen digitos',false,'imagen_programa solamente permite formato alfabetico'),
    Array('imagen_programa',4,'caracteres especiales',false,'imagen_programa debe limitarse a caracteres incluidos ["acentos", "ñ", "espacios"]')
);
</script>
